CFLAGS?=-O2 -g -Wall -W -D__SDRPLAY__
LDLIBS+= -lmirsdrapi-rsp -lpthread -lm
CC?=gcc
PROGNAME=dump1090-sdrplay

all: dump1090-sdrplay

%.o: %.c
	$(CC) $(CFLAGS) -c $<

dump1090-sdrplay: dump1090.o anet.o
	$(CC) -g -o dump1090-sdrplay dump1090.o anet.o $(LDFLAGS) $(LDLIBS)

clean:
	rm -f *.o dump1090-sdrplay
